[package]
name = "cargo-binstall"
repository = "https://github.com/ryankurte/cargo-binutil"
version = "0.1.0"
authors = ["ryan <ryan@kurte.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crates_io_api = "0.6.1"
cargo_metadata = "0.12.1"
tinytemplate = "1.1.0"
tokio = { version = "0.2.24", features = [ "macros" ] }
log = "0.4.11"
structopt = "0.3.21"
simplelog = "0.8.0"
anyhow = "1.0.35"
reqwest = "0.10.9"
tempdir = "0.3.7"
flate2 = "1.0.19"
tar = "0.4.30"
cargo_toml = "0.8.1"
serde = { version = "1.0.118", features = [ "derive" ] }
strum_macros = "0.20.1"
strum = "0.20.0"
dirs = "3.0.1"
