[package]
name = "cargo-binstall"
description = "Rust binary package installer for CI integration"
repository = "https://github.com/ryankurte/cargo-binstall"
documentation = "https://docs.rs/cargo-binstall"
version = "0.3.0"
authors = ["ryan <ryan@kurte.nz>"]
edition = "2018"
license = "GPL-3.0"


[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ format }"
bin-dir = "{ bin }{ format }"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[dependencies]
crates_io_api = "0.7.0"
cargo_metadata = "0.12.2"
tinytemplate = "1.2.0"
tokio = { version = "1.4.0", features = [ "full" ] }
log = "0.4.14"
structopt = "0.3.21"
simplelog = "0.9.0"
anyhow = "1.0.40"
reqwest = { version = "0.11.2", features = [ "rustls-tls" ], default-features = false }
tempdir = "0.3.7"
flate2 = "1.0.14"
tar = "0.4.30"
cargo_toml = "0.8.1"
serde = { version = "1.0.130", features = [ "derive" ] }
strum_macros = "0.20.1"
strum = "0.20.0"
dirs = "3.0.1"
serde_derive = "1.0.118"
crates-index = "0.16.2"
semver = "0.11.0"
xz2 = "0.1.6"
zip = "0.5.11"

[dev-dependencies]
env_logger = "0.8.2"
