[package]
name = "cargo-binstall"
description = "Rust binary package installer for CI integration"
repository = "https://github.com/ryankurte/cargo-binstall"
documentation = "https://docs.rs/cargo-binstall"
version = "0.10.0"
rust-version = "1.61.0"
authors = ["ryan <ryan@kurte.nz>"]
edition = "2021"
license = "GPL-3.0"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ format }"
bin-dir = "{ bin }{ format }"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"
[package.metadata.binstall.overrides.x86_64-apple-darwin]
pkg-fmt = "zip"

[dependencies]
async-trait = "0.1.56"
bytes = "1.2.0"
bzip2 = "0.4.3"
cargo_toml = "0.11.5"
clap = { version = "3.2.14", features = ["derive"] }
crates_io_api = { version = "0.8.0", default-features = false }
dirs = "4.0.0"
flate2 = { version = "1.0.24", default-features = false }
fs4 = "0.6.2"
futures-util = { version = "0.3.21", default-features = false }
home = "0.5.3"
jobserver = "0.1.24"
log = "0.4.17"
miette = { version = "5.1.1", features = ["fancy-no-backtrace"] }
mimalloc = { version = "0.1.29", default-features = false, optional = true }
once_cell = "1.13.0"
reqwest = { version = "0.11.11", features = ["stream"], default-features = false }
scopeguard = "1.1.0"
semver = "1.0.12"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
simplelog = "0.12.0"
strum = "0.24.1"
strum_macros = "0.24.2"
tar = "0.4.38"
tempfile = "3.3.0"
thiserror = "1.0.31"
tinytemplate = "1.2.1"
tokio = { version = "1.20.0", features = ["rt-multi-thread", "process", "sync"], default-features = false }
toml_edit = { version = "0.14.4", features = ["easy"] }
url = "2.2.2"
xz2 = "0.1.7"

# Disable all features of zip except for features of compression algorithms:
# Disabled features include:
#  - aes-crypto: Enables decryption of files which were encrypted with AES, absolutely zero use for
#    this crate.
#  - time: Enables features using the [time](https://github.com/time-rs/time) crate,
#    which is not used by this crate.
zip = { version = "0.6.2", default-features = false, features = ["deflate", "bzip2", "zstd"] }

# zstd is also depended by zip.
# Since zip 0.6.2 depends on zstd 0.10.0, we also have to use 0.10.0 here,
# otherwise there will be a link conflict.
zstd = { version = "0.10.0", default-features = false }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
guess_host_triple = "0.1.3"

[features]
default = ["static", "zlib-ng", "rustls"]

mimalloc = ["dep:mimalloc"]

static = ["bzip2/static", "xz2/static"]
pkg-config = ["zstd/pkg-config"]

zlib-ng = ["flate2/zlib-ng"]

rustls = ["crates_io_api/rustls", "reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]

[dev-dependencies]
env_logger = "0.9.0"

[build-dependencies]
embed-resource = "1.7.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
