[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
[target.aarch64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=ld"]
[target.x86_64h-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=ld"]
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=ld"]
